spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/hearmeout?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USER}
    password: ${DB_PASS}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: true

cookie:
  creation:
    secure: false
    same-site: Lax