server:
  port: ${PORT}
  servlet:
    context-path: /api

spring:
  application:
    name: HearMeOut_Backend
  profiles:
    active: ${SPRING_ACTIVE_PROFILE}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
jwt:
  secret: ${SECRET_KEY}

springdoc:
  swagger-ui:
    path: /docs

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{requestId}] [%X{requestMethod} %X{requestURI}] %-5level %logger - %msg%n"