server:
  port: ${PORT}
  servlet:
    context-path: /api

spring:
  application:
    name: HearMeOut_Backend
  profiles:
    active: ${SPRING_ACTIVE_PROFILE}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
  devtools:
    restart:
      enabled: false
jwt:
  secret: ${SECRET_KEY}

springdoc:
  swagger-ui:
    path: /docs



